#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi
IFS=:
./stest.exe -dqr -n "$cache" "$PATH"
if [ "$?" -eq "0" ]; then
	./stest.exe -flx "$PATH" | sort -u | tee "$cache"
else
	cat "$cache"
fi
